name: Publish Docker
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * 1' # Weekly on Mondays at 10:00
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: 'jdk'
      REPO: 'ukhomeofficedigital/jdk'
    steps:
      - uses: actions/checkout@main
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE }}:latest
      - uses: anchore/scan-action@main
        with:
          image: "${{ env.IMAGE }}:latest"
          fail-build: false
          severity-cutoff: critical
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: ${{ env.REPO}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: quay.io
          cache: true
          snapshot: true
          tags: "${{ github.sha }},latest"
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Github # default: 8398a7@action-slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
